nginx:
  restart: always
  privileged: true
  image: nginx:alpine
  volumes:
    - /opt/docker/data/nginx/data:/etc/nginx/conf.d/mysite.template:rw
    - /opt/docker/data/nginx/config:/etc/nginx/conf:ro
    - /opt/docker/data/nginx/logs:/etc/nginx/logs:rw
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=raytest.com
   - NGINX_PORT=80
#  command: /bin/bash -c \"envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\"
  command: /bin/bash -c \"nginx -g 'daemon off;'\"
